let atributeImages = {
    bald: "👨‍🦲",
    male: "♂️",
    glasses: "👓",
    hat: "👒",
    beard: "🧔",
    moustache: "👨",
    "chin-beard": "🧔🏽",
    "white hair": "👵",
    "blond hair": "👱‍♀️",
    "red hair": "👨‍🦰",
    "brown hair": "🧑‍",
    "black hair": "👩🏻‍🦱",
    "blue eyes": "👁️‍🗨️",
    "big nose": "👃"
  },
  people = {
    Alex: {
      bald: !1,
      male: !0,
      glasses: !1,
      hat: !1,
      beard: !0,
      moustache: !0,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !0,
      "blue eyes": !1,
      "big nose": !1
    },
    Anita: {
      bald: !1,
      male: !1,
      glasses: !1,
      hat: !1,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !0,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !0,
      "big nose": !1
    },
    Peter: {
      bald: !1,
      male: !0,
      glasses: !1,
      hat: !1,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !0,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !0,
      "big nose": !0
    },
    Eric: {
      bald: !1,
      male: !0,
      glasses: !1,
      hat: !0,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !0,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !1
    },
    Charles: {
      bald: !1,
      male: !0,
      glasses: !1,
      hat: !1,
      beard: !0,
      moustache: !0,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !0,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !1
    },
    Sam: {
      bald: !0,
      male: !0,
      glasses: !0,
      hat: !1,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !0,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !1
    },
    Joe: {
      bald: !1,
      male: !0,
      glasses: !0,
      hat: !1,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !0,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !1
    },
    Maria: {
      bald: !1,
      male: !1,
      glasses: !1,
      hat: !0,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !0,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !1
    },
    Philip: {
      bald: !1,
      male: !0,
      glasses: !1,
      hat: !1,
      beard: !0,
      moustache: !1,
      "chin-beard": !0,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !0,
      "blue eyes": !1,
      "big nose": !1
    },
    Richard: {
      bald: !0,
      male: !0,
      glasses: !1,
      hat: !1,
      beard: !0,
      moustache: !0,
      "chin-beard": !0,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !0,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !1
    },
    Susan: {
      bald: !1,
      male: !1,
      glasses: !1,
      hat: !1,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !0,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !1
    },
    Max: {
      bald: !1,
      male: !0,
      glasses: !1,
      hat: !1,
      beard: !0,
      moustache: !0,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !0,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !0
    },
    Alfred: {
      bald: !1,
      male: !0,
      glasses: !1,
      hat: !1,
      beard: !0,
      moustache: !0,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !0,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !0,
      "big nose": !1
    },
    Robert: {
      bald: !1,
      male: !0,
      glasses: !1,
      hat: !1,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !0,
      "black hair": !1,
      "blue eyes": !0,
      "big nose": !0
    },
    Frans: {
      bald: !1,
      male: !0,
      glasses: !1,
      hat: !1,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !0,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !1
    },
    Claire: {
      bald: !1,
      male: !1,
      glasses: !0,
      hat: !0,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !0,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !1
    },
    Paul: {
      bald: !1,
      male: !0,
      glasses: !0,
      hat: !1,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !0,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !1
    },
    Bill: {
      bald: !0,
      male: !0,
      glasses: !1,
      hat: !1,
      beard: !0,
      moustache: !1,
      "chin-beard": !0,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !0,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !1
    },
    David: {
      bald: !1,
      male: !0,
      glasses: !1,
      hat: !1,
      beard: !0,
      moustache: !1,
      "chin-beard": !0,
      "white hair": !1,
      "blond hair": !0,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !1
    },
    Bernard: {
      bald: !1,
      male: !0,
      glasses: !1,
      hat: !0,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !0,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !0
    },
    George: {
      bald: !1,
      male: !0,
      glasses: !1,
      hat: !0,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !0,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !1
    },
    Tom: {
      bald: !0,
      male: !0,
      glasses: !0,
      hat: !1,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !0,
      "blue eyes": !0,
      "big nose": !1
    },
    Herman: {
      bald: !0,
      male: !0,
      glasses: !1,
      hat: !1,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !0,
      "brown hair": !1,
      "black hair": !1,
      "blue eyes": !1,
      "big nose": !0
    },
    Anne: {
      bald: !1,
      male: !1,
      glasses: !1,
      hat: !1,
      beard: !1,
      moustache: !1,
      "chin-beard": !1,
      "white hair": !1,
      "blond hair": !1,
      "red hair": !1,
      "brown hair": !1,
      "black hair": !0,
      "blue eyes": !1,
      "big nose": !1
    },
    total: {
      bald: 0,
      male: 0,
      glasses: 0,
      hat: 0,
      beard: 0,
      moustache: 0,
      "chin-beard": 0,
      "white hair": 0,
      "blond hair": 0,
      "red hair": 0,
      "brown hair": 0,
      "black hair": 0,
      "blue eyes": 0,
      "big nose": 0
    }
  };